package pl.inpost.shipment.api.model

/**
 * Order of statuses - higher number = higher priority
 * 1. CREATED
 * 2. CONFIRMED
 * 3. ADOPTED_AT_SOURCE_BRANCH
 * 4. SENT_FROM_SOURCE_BRANCH
 * 5. ADOPTED_AT_SORTING_CENTER
 * 6. SENT_FROM_SORTING_CENTER
 * 7. OTHER
 * 8. DELIVERED
 * 9. RETURNED_TO_SENDER
 * 10. AVIZO
 * 11. OUT_FOR_DELIVERY
 * 12. READY_TO_PICKUP
 * 13. PICKUP_TIME_EXPIRED
 */
enum class ShipmentStatus(val priority: Int) {
    ADOPTED_AT_SORTING_CENTER(5),
    SENT_FROM_SORTING_CENTER(6),
    ADOPTED_AT_SOURCE_BRANCH(3),
    SENT_FROM_SOURCE_BRANCH(4),
    AVIZO(10),
    CONFIRMED(2),
    CREATED(1),
    DELIVERED(8),
    OTHER(7),
    OUT_FOR_DELIVERY(11),
    PICKUP_TIME_EXPIRED(13),
    READY_TO_PICKUP(12),
    RETURNED_TO_SENDER(9);
}
